# **Machine Learning with Python**

## **TensorFlow**

### Introduction: Machine Learning Fundamentals

Machine Learning is a subset of artificial intelligence.

Rather than giving the program rules, an algorithm finds the rules for us.
$$$$
**Neural Network** - A form of machine learning that uses a layered representation of data.

**Features** - input or information that we have.

**Label** - ouput or information we are trying to find.

### Introduction to TensorFlow

**Tensor** - vector generalized to higher dimensions.

Each tensor has a data type and a shape:
- **data type**: what kind of information is stored in a tensor eg float32, int32, string, etc.
- **shape**: represents the dimension of the data.

In [30]:
# Below is an example of how to create some different tensors.
import tensorflow as tf

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# These tensors have a shape of 1 and are therefore scalars (rank 0)

### Rank/Degree of Tensors

The number of dimensions involved in the tensor.

In [31]:
# Some tensors of higher degrees/ ranks

rank1_tensor = tf.Variable(["test", "ok", "Tim"], tf.string) # An array (rank 1 tensor)
rank2_tensor = tf.Variable([["test", "ok"],["test", "yes"], ["yes", "ya"]], tf.string) # A list inside of a list (rank 2 tensor)

In [32]:
# To determine the rank of a tensor
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of a Tensor

The amount of elements that exist in each dimension.

In [33]:
rank2_tensor.shape

TensorShape([3, 2])

### Changing Shape

The example below shows how to change the shape of a tensor.

In [34]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1)

tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
# this will reshape the tensor to [3,2]
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors

- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of variable all of these tensors are immutable, meaning their value may not change during execution.